config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'questions/index'
  root to: "questions#index"
  get 'questions/page_a'
  get 'questions/page_b'
  get 'questions/page_c'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/type.rb
class Type < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '骨格ストレート' },
    { id: 3, name: '骨格ウェーブ' },
    { id: 4, name: '骨格ナチュラル' },
  ]

  include ActiveHash::Associations
  has_many :users

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :type

  with_options presence: true do
    validates :nickname
    with_options numericality: { other_than: 1 } do
      validates :type_id
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname,:type_id])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def page_a
  end

  def page_b
  end

  def page_c
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kokkakun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>コッカくん</title>
    <link rel="stylesheet" hrel="index.css">
  </head>
  <body>
    <%= render"shared/header"%>

    <div class="contents">
      これはご自身の体型の骨格タイプを知ってもらうためのアプリケーションです。
      <br>ご自身の骨格タイプが分かれば下記のメリットがあります。
    </div>
    
    <div class="merit">
      ①体型の特徴が分かり、それにより筋肉と脂肪のつき方が分かるので、太り方や鍛えると効果的な部位が分かる<br>
      ②似合う服が分かり、その服を着ることでスタイルがよく見えるので、周りの印象を変えることができる
    </div>
    <div class="middle_contents"> 
    ご自身の骨格に合った服装や筋トレをしていただくことで、第一印象で損をする確率を大きく減らすことができます。
    <br>これを機にご自身の骨格を知り、似合う服装を知って頂いて、今後の服選びの参考にしていただければ幸いです。
    </div>
    <div class="bottom_contents">
    ご自身のタイプを診断するために、下記の１０個の質問にお答えください。
    <br>A B Cの中から、ご自身に最も近いと思えるものにチェックをお願いします。
    <br>チェック後は『カウントする』ボタンを押してください。
    </div>
  
  <form>
    <ul class="questions">
    Q1 首の長さは？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 短い
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 長い
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c">C 太くて筋が目立つ
      </li>
    </ul>

    <ul class="questions">
    Q2 鎖骨は？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 目立たない
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 細く、目立つ
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c" >C 大きくて目立つ
      </li>
    </ul>

    <ul class="questions">
     Q3 上半身の厚みは？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 胸板厚め、肩周りはガッチリ
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 胸板薄め、肩まわり華奢
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c" >C 胸板薄い、肩幅広め 筋肉より鎖骨や肩の骨が目立つ
      </li>
    </ul>

    <ul class="questions">
    Q4 腰回りは？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 腰の位置低め くびれは無い方
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 腰の位置低い くびれあり
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c" >C 骨盤付近の骨が出ていて目立つ
      </li>
    </ul>

    <ul class="questions">
    Q5 太もも、膝下の特徴は？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 太ももは太く膝下は細い 骨は真っ直ぐ
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 下半身全体が太い O脚気味
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c" >C 太ももは肉肉しくない すねの骨が太い
      </li>
    </ul>

    <ul class="questions">
    Q6 ひざの皿は？
      <li class="answer">
      <input type="checkbox" name="answer_a" value= "a" >A 小さく目立たない
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_b" value= "b" >B 普通 丸い
      </li>
      <li class="answer">
      <input type="checkbox" name="answer_c" value= "c" >C 大きくて目立つ 
      </li>
    </ul>

   <ul class="questions">
   Q7 手の特徴は？
     <li class="answer">
     <input type="checkbox" name="answer_a" value= "a" >A 小さく厚い 指が短い
     </li>
     <li class="answer">
     <input type="checkbox" name="answer_b" value= "b" >B 普通 丸い 
     </li>
     <li class="answer">
     <input type="checkbox" name="answer_c" value= "c" >C 大きく筋が目立つ 第二関節が一番太い
     </li>
   </ul>

  <ul class="questions">
  Q8 手首の特徴は？
    <li class="answer">
    <input type="checkbox" name="answer_a" value= "a" >A 細くて丸い
    </li>
    <li class="answer">
    <input type="checkbox" name="answer_b" value= "b" >B 平べったく薄い（楕円型）
    </li>
    <li class="answer">
    <input type="checkbox" name="answer_c" value= "c" >C くるぶしが目立つ長方形
    </li>
  </ul>
   
   <ul class="questions">
   Q9 太ると肉がつきやすいのは？
     <li class="answer">
     <input type="checkbox" name="answer_a" value= "a" >A 二の腕 へそ周り
     </li>
     <li class="answer">
     <input type="checkbox" name="answer_b" value= "b" >B 下っ腹 下半身
     </li>
     <li class="answer">
     <input type="checkbox" name="answer_c" value= "c" >C 全体的に太ってガタイが良くなる
     </li>
   </ul>

  <ul class="questions">
  Q10 苦手なファッションは？
    <li class="answer">
    <input type="checkbox" name="answer_a" value= "a" >A ハイネックは着太りする
    </li>
    <li class="answer">
    <input type="checkbox" name="answer_b" value= "b" >B 胸元が開いた服は貧相に見える
    </li>
    <li class="answer">
    <input type="checkbox" name="answer_c" value= "c" >C タイトな服は骨が目立つ
    </li>
  </ul>
  <div class="count">
    <button id="btn" type="button" class="count">カウントする</button>
   </div>
</form>

<div class="category">
 Aが多い人は下記のページA、Bが多い人はページB、Cが多い人はページCのリンクをクリックしてください。
 <br>もし、A、B、Cのいずれかのチェック数が同じだった場合はミックスタイプになります。
 <br>例えばAが5点、Bが5点の場合はページCの服装を避けるようにしてください。
</div>

<div class="page_a">
  <%=link_to questions_page_a_path do %>
   <button class="btn_page_a">ページA</button>
   <%end%>
</div>
<div class="page_b">
   <%=link_to questions_page_b_path do%>
   <button class="btn_page_b">ページB</button>
   <%end%>
</div>
<div class="page_c">
   <%=link_to questions_page_c_path do %>
   <button class="btn_page_c">ページC</button>
   <%end%>
</div>
<%= render"shared/footer"%>
  </body>
</html>

app/views/questions/page_a.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>骨格ストレートタイプ</title>
    <link rel="stylesheet" hrel="page_a.css">
  </head>
  <body class="straight">
    <%= render"shared/header"%>
    <div class="type">
      Aが多かったあなたは、<span class="red">『骨格ストレートタイプ』</span>です！
      <br>王様タイプとも呼ばれ、スーツが似合う人が多く、特徴は下記の通りです。
    </div>

      <ul class="characteristics">
      <li>胸板が厚い/肩まわりガッチリ</li>
      <li>上半身にボリューム/首が短い</li>
      <li>ぽっちゃりに見える、もしくは筋肉質のマッチョ</li>
      <li>太ももは肉感的/膝下は細い</li>
      <li>腰の位置が高い/脚長</li>
      <li>体に比べ手足が小さく、厚みがある</li>
      <li>持たれやすいイメージは、正統派 真面目 健康的 強い 頼りがいがある。</li>
      <li>このタイプの有名人は、松平健さん 香川照之さん 渡辺謙さんがいます。</li>
      </ul>
    </div>
    
    <div class="table">
      ■筋トレについて
      </div>
    <div class="muscle">
    骨格ストレートタイプの人は腹筋を重点的に鍛えましょう。
    <br>骨格ストレートタイプの体型はりんご体型の人が多く、くびれがないとぽっちゃりに見えてしまいます。
    <br>逆にウエストを締めると体にメリハリが出ます。
    <br>ちなみに、太るときはりんごの形のまま太るため、顔 お腹 腕 前太ももが太る傾向にあります。
    </div>

    <div class="table">
    ■似合う服装について
    </div>
    <div class="coordination">
    体自体に存在感があるため、シンプルイズベストがおすすめ。
    <br>上半身に厚みがある分、着太りするのでジャストサイズ
    <br>透け感のある薄手の服などは必要以上に筋肉を強調するので厚地で上質なデザインが似合う
    </div>
    <div class="table">

    ■トップスについて
    </div>
    <div class="top">
    厚みのある胸元をすっきり見せるため、首回りの空いている服装 Vネック
     <br>重ね着は着太りする。上半身の厚みを隠してくれるジャケットが似合う
     <br>薄手の生地はムチムチ感が出るため、シャツやTシャツは厚地/光沢のあるもの
    </div>
    <div class="table">
    ■ボトムスについて
    </div>
    <div class="bottom">
    スキニーよりも筋肉質の太ももをあまり強調しないストレートパンツ
    <br>中央に縦線の入っているスラックスも似合う
    <br>短パンなら細い膝下を見せる膝上の短パン これも太ももの筋肉を強調しないように厚地や上質な素材を選ぶ
    </div>

    <div class="table">
    ■似合う柄について
    </div>
    <div class="pattern">
    直線を意識
    <br>幅太め 色コントラスト強め 大きめの柄
    <br>体に存在感があるため、シンプルな柄がおすすめ
    </div>

    <div class="table">
    ■NGな服装について
    </div>
    <div class="ng">
    首が短いのでハイネックは苦しそうに見える
    <br>柔らかい素材は着太りする
     <br>オーバーサイズすぎる服は体のボリュームが悪目立ちし、怖そうな印象を与える
     <br><%= image_tag "straightng.jpg", class: "example"%>
    </div>

   <div class="table">
    ■似合う服の一例
    </div>
    <div class="image">
       <%= image_tag "straight1.jpg", class: "example"%>
       <p>ストレートタイプは、柔らかい服を纏うと筋肉が張って見えるので、ハリのある上質な服がおすすめです。
       <br>そこで、スーツ地のセットアップ。ネックラインの開いたTシャツで肉感的な男らしさも薫らせて。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "straight2.jpg", class: "example"%>
       <p>ぴったりした体のラインを強調する形は苦手なので、ストンとしたベーシックなシルエットを選ぶのがおすすめです。
       <br>シャツならストレスを感じないジャストサイズ、ジーンズなら王道のストレートで。ハリのある生地感も◎。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "straightsuit.jpg", class: "example"%>
       <p>ストレートタイプの男性に似合うスーツのジャケットは、着丈長めの、ウエスト絞り付きジャケットがおすすめです！
          <br>上半身のフィット感を重視する必要があるため、アメリカンスーツの特徴である、着丈が長く、深いVゾーンや太いラペル幅などの重厚でゆとりあるフレームを残しながら、
          適度に絞りが入ったスタイリッシュなデザインのジャケットがオススメです。
        </p>
    </div>

<div class="return">
   <%=link_to root_path do %>
   <button class="btn_root">トップページへ戻る</button>
   <%end%>
</div>
    <%= render"shared/footer"%>
    <body>
    </html>

app/views/questions/page_b.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>骨格ウェーブタイプ</title>
    <link rel="stylesheet" hrel="page_b.css">
  </head>
  <body class="wave">
    <%= render"shared/header"%>
    <div class="type">
      Bが多かったあなたは、<span class="blue">『骨格ウェーブタイプ』</span>です！
      <br>王子様タイプとも呼ばれ、首が長くて華奢な人が多く、特徴は下記の通りです。
    </div>

      <ul class="characteristics">
      <li>胸板が薄くて華奢</li>
      <li>筋肉が付きにくく肌が柔らかい</li>
      <li>首が長い</li>
      <li>撫で肩</li>
      <li>ウエストが細くてくびれがある</li>
      <li>腰の位置低い/足が短め</li>
      <li>下半身太りしやすい</li>
      <li>持たれやすいイメージは、かわいい、甘い、優しい、ソフト、繊細</li>
      <li>このタイプの有名人は、高橋一成さん 山下智久さん 二宮和也さんがいます。</li>
      </ul>
    </div>
    
    <div class="table">
      ■筋トレについて
      </div>
    <div class="muscle">
    骨格ウェーブタイプの人は三角筋を重点的に鍛えましょう。
    <br>下半身にボリュームがあるため、上半身を鍛えるとバランスが良くなります。
    <br>なで肩で肩幅が狭い人が多いので、三角筋を重点的に鍛えて肩幅を広げることで肩の傾斜も水平に近づいて、なで肩も解消されます。
    <br>骨格ウェーブタイプの体型は洋なし体型の人が多く、洋なし体型のまま太るため上半身は華奢だが下腹、お尻、下半身全体に肉が付くタイプです。
    </div>

    <div class="table">
    ■似合う服装について
    </div>
    <div class="coordination">
    タイトでコンパクトなシルエットが似合うためタイト、またはジャストサイズがおすすめ。
    <br>薄くて柔らかい素材で着丈、袖、裾は短めにしましょう。
    </div>
    <div class="table">
    ■トップスについて
    </div>
    <div class="top">
    キーワードは上半身にボリュームを！
     <br>華奢なのでカーディガンなどの重ね着もおすすめ！
     <br>首が長いため、鎖骨周りが寂しい印象にならないように首元が空いていない服装が似合う。
     <br>下に重心がある体型のため、上半身に主張のある柄服/襟のある服
     <br>柄や色を持ってきて見る人の視線を上に持っていく
     <br>体が薄くて柔らかい印象なので透け感/ソフト生地が似合う
     <br>腰の位置が低いためトップスの丈を短くしたり、シャツをズボンにインして腰の位置を高く見せる
     <br>手首も細めなので、短め袖、丈にするとオシャレ感がアップ
    </div>
    <div class="table">
    ■ボトムスについて
    </div>
    <div class="bottom">
    コンパクトに見えるスキニータイプ、柔らかい生地が似合うのでストレッチが効いたスキニー
    <br>九分丈パンツで重心を上に持っていける、足首を見せると美脚に見える
    <br>短パンなら膝を隠すと短足に見えるので膝上パンツが似合う
    </div>

    <div class="table">
    ■似合う柄について
    </div>
    <div class="pattern">
    線なら細い線
    <br>色コントラスト弱め 柄は細かい柄
    </div>

    <div class="table">
    ■NGな服装について
    </div>
    <div class="ng">
    ルーズパンツ
    <br>元々下半身にボリュームがあるため、さらに下半身にボリュームを持たせてしまう服装はNG
    <br><%= image_tag "waveng.jpg", class: "example"%>
    </div>

    <div class="table">
    ■似合う服の一例
    </div>
    <div class="image">
       <%= image_tag "wave1.jpg", class: "example"%>
       <p>ウェーブタイプの体の柔らかな曲線を活かすには、フィット感のあるテーラードジャケットやスキニータイプが最適です。
       <br>華奢な上半身を男らしく飾るトップスのレイヤードなど、足し算コーデで胸周りにアクセントを。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "wave2.jpg", class: "example"%>
       <p>体が細く、華奢。そんな貧相な印象もつきまとうので、総柄のシャツでアクセントを作ることがおすすめ。
       <br>ただし柄は大味にならないような細かい柄が必須。下半身は、すっきりとしたフォルムのスニーカーとパンツでシュッと見せましょう。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "wavesuit.jpg", class: "example"%>
       <p>骨格診断ウェーブタイプの男性は、柔らかく胸板にあまり厚みのない華奢な上半身です。
        <br>Vゾーンの空きを浅めに、着丈を短めにすることで、薄い胸元を立体的に演出することができます。
        <br>さらに、高めに絞りが効き、ラペル幅が狭いジャケットの方がバランスが良いです。
        <br>ウェーブタイプの男性は固い素材が苦手です。なるべく柔らかい素材のものを選びましょう。
       </p>
    </div>
<div class="return">
   <%=link_to root_path do %>
   <button class="btn_root">トップページへ戻る</button>
   <%end%>
</div>
   <%= render"shared/footer"%>
    <body>
    </html>

app/views/questions/page_c.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <title>骨格ナチュラルタイプ</title>
    <link rel="stylesheet" hrel="page_c.css">
  </head>
  <body class="natural">
    <%= render"shared/header"%>
    <div class="type">
      Cが多かったあなたは、<span class="green">『骨格ナチュラルタイプ』</span>です！
      <br>モデルタイプとも呼ばれ、カジュアルな服装が似合う人が多く、特徴は下記の通りです。
    </div>

      <ul class="characteristics">
      <li>骨格がしっかりしている</li>
      <li>骨/関節/筋肉/血管が目立つ</li>
      <li>首筋/鎖骨/喉仏が目立つ</li>
      <li>肩幅が大きい</li>
      <li>手足が大きい</li>
      <li>太るとガタイが良くなる</li>
      <li>持たれやすいイメージは、ラフ、ワイルド、独自的、異端児、冒険的</li>
      <li>このタイプの有名人は、オダギリジョーさん 阿部寛さん 江口洋介さんがいます。</li>
      </ul>
    </div>
    
    <div class="table">
      ■筋トレについて
      </div>
    <div class="muscle">
    骨格ナチュラルタイプの人は太りたいなら上下にバランスよく筋トレ
    <br>痩せたいなら、どこかの部位を鍛えるよりかは全体的に体を動かす水泳やランニングのような有酸素運動
    <br>骨格ナチュラルタイプはバナナ体型の人が多く、筋肉や脂肪より骨や筋が目立ちます。
    <br>太るときは上と下が一緒に太るため、ぽっちゃりというよりかは、ガタイが良くなります。
    <br>筋肉も脂肪も付きにくく、骨が目立つため太りたいという人が多い。
    </div>

    <div class="table">
    ■似合う服装について
    </div>
    <div class="coordination">
    個性的/カジュアル デニムなどの定番のカジュアルが得意です。
    <br>しっかりとした骨や関節を目立たせないために着丈、袖、裾は長め 
    <br>オーバーサイズ命!
    </div>
    <div class="table">
    ■トップスについて
    </div>
    <div class="top">
    大きめの服、長めの丈、袖
     <br>肩幅が広いので痩せている人でも服に着られている感が出ない。
     <br>骨が目立つと貧相なイメージなので露出が少ない服
     <br>胸板は薄い方なので重ね着しても着太りしない
     <br>カジュアル感が一気に出るフード付きの服
    </div>
    <div class="table">
    ■ボトムスについて
    </div>
    <div class="bottom">
    骨感があまり強調されない、裾長め、ワイドパンツ、チノパン
    <br>ジーンズ、ダメージ加工もOK！
    </div>

    <div class="table">
    ■似合う柄について
    </div>
    <div class="pattern">
    個性の出せるエスニック柄、ランダムな柄、細かすぎない柄
    <br>基本的に柄物は似合いますが、体格がしっかりしているため小さいドットなどの細かすぎる柄は合わない傾向にあります。
    </div>

    <div class="table">
    ■NGな服装について
    </div>
    <div class="ng">
    タイトな服、露出多めの服
    <br>骨感、関節、筋が目立って不健康に見えるため。
    <br><%= image_tag "naturalng.jpg", class: "example"%>
    </div>
    
    <div class="table">
    ■似合う服の一例
    </div>
    <div class="image">
       <%= image_tag "natural1.jpg", class: "example"%>
       <p>ナチュラルタイプの特徴である“骨っぽさ”を上手に活かすには、ゆったりしたサイズ感のアイテムでトータルコーデ。
       <br>空気をはらむシルエットで、体が持つフレーム感が自然に活かされるので、大人らしい余裕も漂います。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "natural2.jpg", class: "example"%>
       <p>キレイめなコーディネイトもカジュアルな素材を選ぶと、骨っぽさのある「ナチュラルタイプ」にしっくりなじみます。
       <br>ジーンズはややゆとりのあるものを選ぶのがコツ。体の凹凸が際立たなくなるのでオススメです。
       </p> 
    </div>
    <div class="image">
       <%= image_tag "naturalsuit.jpg", class: "example"%>
       <p>Vゾーンの空きを深くし、ボックスシルエットor絞りの位置が低いデザインのものを選ぶことで、肩のフレーム感を強調しないシルエットでジャケットを着こなすことができます。
       <br>こういった形は、アメリカンスーツに多いデザインです。大きめなサイズ感をスタイリッシュに着こなせるのはナチュラルの男性の大きな特徴です。
       </p>
    </div>
<div class="return">
   <%=link_to root_path do %>
   <button class="btn_root">トップページへ戻る</button>
   <%end%>
</div>
    <%= render"shared/footer"%>
    <body>
    </html>

app/views/shared/_footer.html.erb
 <footer>
 </footer>

app/views/shared/_header.html.erb
<header>
<div class= "nav">
  <div>
   <%= link_to "骨格診断ツール コッカくん", root_path,class: :title%>
  </div>

<% if user_signed_in? %>
 <div class= "nav_right">
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: :nav_btn%>
  <%= link_to "#{current_user.nickname}", "#",class: :nav_btn%>
 </div>
 <%else%>
 <div class= "nav_right">
  <%= link_to "ログイン",new_user_session_path,class: :nav_btn%>
  <%= link_to "新規登録",new_user_registration_path,class: :nav_btn%>
 </div>
<%end%>
</header>